### ISSUE TITLE
rowtojson 没办法转吗

### ISSUE THREAD

**Issue by XuanmoFeng** [zaobao/flink-brickhouse#1]

**Comment by zaobao** [comment]
改了下，支持了

**Comment by XuanmoFeng** [comment]
json2row 是不也可以？

**Comment by zaobao** [comment]
json2row，简单的单层的row问题不大
嵌套的row比较复杂，查了flink-json包，没法发现有现成的工具
如果重写大半个json序列化工具（类似gson这种）挺费劲的，大概需要两周的开发和测试时间，我也不太倾向重复造轮子
放最后搞吧，优先实现更常用的函数

这个项目里的json功能，在最新flink里应该都内建支持了吧，只是因为我还在用1.14，所以需要自己写UDF

**Comment by XuanmoFeng** [comment]
好吧，json2row 这个感好复杂
